---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: InfrastructureServices@wwt.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-staging-account
    solvers:
    - selector: {}
      dns01:
        rfc2136:
          nameserver: 172.20.0.48:53
          tsigKeyName: rancher.k8s.wwt.com
          tsigAlgorithm: HMACSHA256
          tsigSecretSecretRef:
            name: tsig-key
            key: tsig-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: InfrastructureServices@wwt.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-account
    solvers:
    - selector: {}
      dns01:
        rfc2136:
          nameserver: 172.20.0.48:53
          tsigKeyName: rancher.k8s.wwt.com
          tsigAlgorithm: HMACSHA256
          tsigSecretSecretRef:
            name: tsig-key
            key: tsig-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ca:
    secretName: ca-key-pair
